api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: ":443"
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    watch: true
    filename: /config/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'alibi@putyourmailadress.here'
      storage: 'acme.json'
      tlsChallenge: {}