api:
  dashboard: true
  insecure: false

ping: {}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
  file:
    watch: true
    filename: /config/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'your-email@example.com'  # Replace with your actual email
      storage: 'acme.json'
      tlsChallenge: {}

log:
  level: INFO

accessLog: {}